### PR TITLE
With Melange 3.0, OCaml 5 and styled-ppx

### PR DESCRIPTION
**Pull request by ManasJayanth**
Some more notes

1. Latest server-reason-react needs ocaml 5, but dream 1.0.0-alpha4 doesn't support ocaml 5. Hence bumped dream.
2. Pinned melange-compiler-libs doesn't support ocaml 5. Turns out we dont need it anymore.
3. Pinned melange needs melange-compiler-libs that doesn't work with ocaml 5
4. rescript-syntax only works with melange-dev. Not absolutely necessary for this repo
5. Pinned reason needs <5.1.0. Hence, bumped it.
6. Removed reactjs-jsx-ppx as it's deprecated.

### CODE REVIEW

**Review by davesnx — APPROVED** [review]

**Comment by ManasJayanth** [comment]
@davesnx Ready for review!

**Comment by ManasJayanth** [comment]
I'll update to Melange 4 in a followup PR

**Comment by ManasJayanth** [comment]
Simply upgrading to Melange 4. doesn't seem to break anything. Manual testing recommended. Page loads fine for me and works.

**Comment by ManasJayanth** [comment]
There seems to be "Flash of unstyled text". Is this normal, @davesnx ?

**Comment by davesnx** [comment]
That shouldn't happen, but can't see it. Let me merge it and see if deploy version works.

**Pull request merged**
